parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended

rules:
  prettier/prettier: error
  react/react-in-jsx-scope: off
  comma-dangle: ['error', 'never']

plugins:
  - prettier
